### ISSUE TITLE
RFE: watchdog option in subtest.yml for panic

### ISSUE THREAD

**Issue by jencce** [tcler/bkr-client-improved#26]
To tell the watchdog to ignore, reboot or do nothing when detected panic.

      <watchdog panic="ignore"/>

      <watchdog panic="reboot"/>

      <watchdog panic="None"/>

**Comment by tcler** [comment]
> To tell the watchdog to ignore, reboot or do nothing when detected panic.
> 
> ```
>   <watchdog panic="ignore"/>
> 
>   <watchdog panic="reboot"/>
> 
>   <watchdog panic="None"/>
> ```

https://github.com/tcler/bkr-client-improved/commit/604346c062c74ca81836b3d542470f64b2052ce6
